### ISSUE TITLE
Lightsaber and Robolectrics causes java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by b-demuth** [MichaelRocks/lightsaber#6]
Hi,
I recently started migrating a project from Dagger 1 to lightsaber and so far, I'm loving it. Great job!

However, all our unit tests are robolectric based and when I initialize an Injector in our App instance within a unit test, I get a NoClassDefFoundError. Seems like robolectric isn't able to find the generated classes, see the stacktrace below..

java.lang.NoClassDefFoundError: io/michaelrocks/lightsaber/InjectionDispatcher
	at io.michaelrocks.lightsaber.Lightsaber$DefaultConfigurator.configureInjector(Lightsaber.java:131)
	at io.michaelrocks.lightsaber.Lightsaber.createInjectorInternal(Lightsaber.java:76)
	at io.michaelrocks.lightsaber.Lightsaber.createInjector(Lightsaber.java:47)

Any idea about how to make the generated classes available to Robolectric?
A workaround would probably be to copy files around in a gradle task, but I'd have to take care of build variants and stuff, so this doesn't sound like fun..

**Comment by b-demuth** [comment]
Hi @MichaelRocks,
thanks for the quick reply!
To be honest I don't quite understand the scope of this problem. Wouldn't it suffice to be able to configure input directories for code processing at compile time and output directories for generated classes so that Robolectric can find them?
I'm probably missing sth. important, cause I don't really know how processing works.
For now I think I'll go with either dagger 2 (which produces too much boilerplate imho) or toothpick (which doesn't seem to provide compile-time safety). Please let me know if I can contribute to help solve this issue.
Should instrumentation tests work?

**Comment by MichaelRocks** [comment]
Tests should work now.

**Comment by b-demuth** [comment]
Hi, thanks for working on this! I still have an issue executing the unit tests:
java.lang.ClassCastException: package.MyComponent cannot be cast to io.michaelrocks.lightsaber.InjectorConfigurator
	at io.michaelrocks.lightsaber.Lightsaber.createInjectorInternal(Lightsaber.java:58)
	at io.michaelrocks.lightsaber.Lightsaber.createInjector(Lightsaber.java:35)

For some reason, the Component doesn't seem to be processed for unit tests. Creating an injector from the same component in production code works fine.

**Comment by b-demuth** [comment]
Btw: how hard would it be to define a Component as "default" instead of a module, or use Components in the "ProvidedBy" annotation? I think it would be more consistent and help me achieve a simpler configuration.

**Comment by b-demuth** [comment]
I've investigated a little further.. said ClassCastException happens, when I try to execute a unit test in an Android project. As I said earlier, we use Robolectric for this, but I don't think Robolectric is related to the issue at hand. I can reproduce the issue by starting from your sample-android-kotlin project and adding a unit test there.

**Comment by MichaelRocks** [comment]
@b-demuth Hi and thank you for reporting the issue. Unit tests should work for Android projects and if they don't it's a bug. I'll take a look at it soon.

What about not using components in `@ProvidedBy` I did it intentionally because the module is what actually provides dependencies and not the component. But that's from the internal point of view while user's point of view may differ. I need to think if it doesn't break anything. And what don't you like about default modules?
